name: Release

on:
  workflow_dispatch:
    inputs:
      version:
        type: string
        required: true
        description: "Version number"

jobs:
  release:
    runs-on: ubuntu-20.04
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: '3.8.6'
    - name: Install tools dependencies
      run: sudo apt-get install unrar
    - name: Install python dependencies
      run: pip install -r requirements.txt
    - name: Run build
      run: python build.py
    - uses: ncipollo/release-action@v1
      with:
        name: "trajectory datasets"
        artifacts: "./builds/*.zip"
        tag: "v${{ github.event.inputs.version }}"
        commit: "main"
